# list of packages/ libraries used for the PyVis workshop
# use 'conda env create -f environment.yml' or 'mamba env create -f environment.yml'
# to create the environment

name: pyvis

channels:
    - conda-forge
    - nodefaults

dependencies:
    - python=3.11
    - pip
    # plotting and data handling
    - cartopy
    - cmcrameri
    - geopandas
    - matplotlib
    - netCDF4
    - numpy
    - pandas
    - pooch
    - psy-maps
    - scipy
    - seaborn
    - xarray
    # code formatting
    - black
    - isort
    # jupyter
    - ipykernel
    - ipympl
    - jupyterlab
    - jupyterlab_code_formatter
    - pip:
        - https://github.com/mathause/mplotutils/archive/v0.3.1.zip
        - git+https://github.com/C2SM/iconarray@v0.1.19#egg=iconarray
