# list of packages/ libraries used for the PyVis workshop
# use 'conda env create -f environment.yml' or 'mamba env create -f environment.yml'
# to create the environment

name: pyvis

channels:
    - conda-forge
    - nodefaults

dependencies:
    - python=3.11
    - pip
    # plotting and data handling
    - cartopy=0.21.1
    - cmcrameri
    - geopandas
    - matplotlib
    - netCDF4
    - numpy
    - pandas
    - pooch
    - psy-maps=1.4.2
    - psy-reg=1.4.0
    - psy-simple=1.4.1
    - psyplot=1.4.3
    - scipy
    - seaborn
    - xarray
    # code formatting
    - black
    - isort
    # jupyter
    - ipykernel
    - ipympl
    - jupyterlab
    - jupyterlab_code_formatter
    - eccodes
    - pip:
        - https://github.com/mathause/mplotutils/archive/v0.4.0.zip
        - iconarray==0.3.2
